// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGKfRgYkljfAJ2JeiDTljBLe-xXN6tEBY',
    appId: '1:887551378633:web:9d36072c93d6f834bab918',
    messagingSenderId: '887551378633',
    projectId: 'whatsapp-clone-f41be',
    authDomain: 'whatsapp-clone-f41be.firebaseapp.com',
    storageBucket: 'whatsapp-clone-f41be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyas9qj0zVz4nCl8_T9VesxVP1VIyFWtI',
    appId: '1:887551378633:android:4e6bfbffa22db87abab918',
    messagingSenderId: '887551378633',
    projectId: 'whatsapp-clone-f41be',
    storageBucket: 'whatsapp-clone-f41be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOb7xMyMHQMlQgchg9o-EJPz-ZuJaFQYk',
    appId: '1:887551378633:ios:48c459e46dc99b7fbab918',
    messagingSenderId: '887551378633',
    projectId: 'whatsapp-clone-f41be',
    storageBucket: 'whatsapp-clone-f41be.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOb7xMyMHQMlQgchg9o-EJPz-ZuJaFQYk',
    appId: '1:887551378633:ios:48c459e46dc99b7fbab918',
    messagingSenderId: '887551378633',
    projectId: 'whatsapp-clone-f41be',
    storageBucket: 'whatsapp-clone-f41be.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
